<?php

namespace Modules\Core\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Core\Models\Language;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Modules\Core\Console\Commands\SyncLocalizationCommand;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $isTenant = function_exists('tenant') && tenant('id');
        $context = $isTenant ? "Tenant (" . tenant('id') . ")" : "Central Base";

        $this->command->info("\n🌍 Initializing Localization for: {$context}");

        // 1. Ensure physical JSON files exist on disk before syncing
        $this->bootstrapPhysicalFiles();

        // 2. Register core languages in the database
        $coreLanguages = [
            ['name' => 'English', 'code' => 'en', 'is_active' => true, 'is_default' => true],
            ['name' => 'Amharic', 'code' => 'am', 'is_active' => true, 'is_default' => false]
        ];

        foreach ($coreLanguages as $langData) {
            Language::updateOrCreate(['code' => $langData['code']], $langData);
        }

        // 3. 🚀 THE ULTIMATE FIX: Safely check if the command is registered in this process.
        $commands = Artisan::all();
        if (!isset($commands['localization:sync'])) {
            $this->command->warn("! [NOTE] Manually registering sync command for this process...");

            // Resolve the Kernel and register the modular command class directly
            app(\Illuminate\Contracts\Console\Kernel::class)->registerCommand(app(SyncLocalizationCommand::class));
        }

        $this->command->info("⏳ Triggering localization sync...");

        // 4. Execute the sync command
        Artisan::call('localization:sync');

        // 5. Output the result using standard command helpers
        $this->command->line(Artisan::output());
        $this->command->info("✅ Localization matrix initialized and synced.");
    }

    /**
     * Create default JSON language files if they don't exist.
     */
    protected function bootstrapPhysicalFiles(): void
    {
        $isTenant = function_exists('tenant') && tenant('id');
        $langPath = $isTenant ? storage_path('app/lang') : base_path('lang');

        $defaultMatrix = [
             'en' => [
                'global' => [
                    'cancel' => 'Cancel',
                    'update' => 'Update',
                    'provision' => 'Provision',
                    'delete' => 'Delete',
                    'purge' => 'Purge',
                    'clear' => 'Clear',
                    'save_changes' => 'Save Changes',
                    'page_tour' => 'Page Tour',
                    'clearance_denied' => 'Clearance Denied',
                    'lacks_permission' => 'Your current access token lacks the required',
                    'capability' => 'capability.',
                    'operation_failed' => 'Operation failed.',
                    'online' => 'Online',
                    'suspended' => 'Suspended',
                    'active' => 'Active',
                    'locked' => 'Locked',
                    'restored' => 'Restored',
                    'created' => 'Created',
                    'updated' => 'Updated',
                    'deleted' => 'Deleted',
                    'viewed' => 'Viewed',
                    'exported' => 'Exported',
                    'copied' => 'Copied',
                    'printed' => 'Printed',
                    'access_denied' => 'Access Denied',
                    'actions' => 'Actions',
                    'view' => 'View Details',
                    'edit' => 'Edit',
                    'all' => 'All',
                    'more' => 'more',
                ],
                'auth' => [
                    'login' => 'Sign In',
                    'logout' => 'Sign Out',
                    'failed' => 'These credentials do not match our records.'
                ],
                'nav' => [
                    'dashboard' => 'Dashboard',
                    'tenants' => 'Node Management',
                    'security' => 'Identity & Access',
                    'audit_logs' => 'System Audit Logs',
                    'storage' => 'Storage',
                    'settings' => 'Settings',
                    'profile' => 'Profile Settings',
                    'control_hub' => 'Control Hub',
                    'disconnect' => 'Disconnect Node',
                    'theme' => 'Theme',
                    'close' => 'Close',
                    'settings_general' => 'General',
                    'settings_general_desc' => 'Basic system configuration.',
                    'settings_security_desc' => 'Authentication and access policies.',
                    'settings_loc' => 'Localization',
                    'settings_loc_desc' => 'Manage dynamic system languages.',
                    'settings_notif' => 'Notifications',
                    'settings_notif_desc' => 'Email and system alerts.',
                    'settings_locked' => 'Configuration Locked',
                    'settings_audit_msg' => 'The matrix is currently undergoing a security audit. Modules will be unlocked in the next patch.',
                ],
                'topbar' => [
                    'search' => 'Search system...',
                    'system_tour' => 'System Tour',
                    'change_language' => 'Change Language',
                    'select_language' => 'Select Language',
                    'my_account' => 'My Account',
                    'profile_settings' => 'Profile Settings'
                ],
                'dashboard' => [
                    'node' => 'NODE',
                    'plan' => 'Plan',
                    'description' => 'System telemetry, access control, and real-time operations.',
                    'realtime_activity' => 'Realtime Activity',
                    'revenue_viz' => '[ Revenue Visualization Mounted Here ]',
                    'system_metrics' => 'System Metrics',
                    'gross_revenue' => 'Gross Revenue',
                    'active_staff' => 'Active Staff',
                    'pending_tasks' => 'Pending Tasks',
                    'recent_logs' => 'Recent Audit Logs',
                    'no_activity' => 'No recent activity detected.',
                    'storage_desc' => 'Tenant-aware file systems operating at optimal capacity.',
                    'decrypting' => 'Decrypting Node Telemetry...',
                    'connection_failed' => 'Node Connection Failed',
                    'connection_error' => 'Failed to connect to telemetry.'
                ],
                'localization' => [
                    'title' => 'Matrix Manager',
                    'publish_project' => 'Publish Project',
                    'system_folders' => 'System Language Folders',
                    'master_source' => 'MASTER SOURCE',
                    'set_master' => 'Set as Master Source',
                    'purge_lang_tooltip' => 'Purge Language',
                    'purge_lang_title' => 'Purge Language Matrix?',
                    'purge_lang_desc' => 'CRITICAL WARNING: Are you sure you want to completely purge the',
                    'purge_lang_desc2' => 'language matrix? This will destroy all translations and physical files for this language. This action cannot be undone.',
                    'edit_dict' => 'Edit Dictionary',
                    'register_new' => 'REGISTER NEW LANGUAGE FOLDER',
                    'create_lang' => 'Create Language',
                    'lang_name_placeholder' => 'Language Name (e.g. Amharic)',
                    'iso_code_placeholder' => 'ISO Code (e.g. am)',
                    'establish' => 'Establish',
                    'node' => 'Node',
                    'folder' => 'Folder:',
                    'filter_matrix' => 'Filter matrix...',
                    'publish_btn' => 'Publish',
                    'add_key_btn' => 'Add Key',
                    'json_files' => 'JSON Files',
                    'all_files' => 'All Files',
                    'system_id' => 'System Identifier',
                    'master' => 'Master',
                    'entry' => 'Entry',
                    'no_keys' => 'No system keys found in this view',
                    'input_string' => 'Input string...',
                    'purge_key_tooltip' => 'Purge Key',
                    'purge_key_title' => 'Purge System Key?',
                    'purge_key_desc' => 'Are you sure you want to permanently delete',
                    'purge_key_desc2' => 'from the global system? This will remove it from all language matrices.',
                    'add_key_title' => 'Add Key to File',
                    'global_sys_key' => 'Global System Key',
                    'file_name' => 'File Name',
                    'file_name_placeholder' => 'e.g. auth',
                    'key_name' => 'Key Name',
                    'key_name_placeholder' => 'e.g. login_title',
                    'master_value' => 'Master Value',
                    'master_value_placeholder' => 'The text to translate...',
                    'discard' => 'Discard',
                    'inject_key' => 'Inject Key',
                    'toast_key_req' => 'Key and source text are required',
                    'toast_group_req' => 'File group cannot be empty',
                    'toast_key_added' => 'Key added to',
                    'toast_key_purged' => 'purged.',
                    'toast_lang_purged' => 'completely purged from the system.',
                    'toast_compiling' => 'Compiling JSON Files...',
                    'toast_published' => 'Folders & Files Published Successfully!',
                    'toast_failed' => 'Compilation Failed',
                    'engine_title' => 'Localization Engine',
                    'engine_desc' => 'Manage dynamic translations and language files for this node.',
                ],
                'security' => [
                    'identity' => 'Identity',
                    'access' => 'Access',
                    'node_clearance' => 'Node Clearance',
                    'denied_desc' => 'Your current clearance level does not permit access to the Identity & Security matrix.',
                    'tab_operators' => 'Operators',
                    'tab_roles' => 'Access Roles',
                    'tab_permissions' => 'Permissions',
                    'matrix_tour' => 'Matrix Tour',
                    'encrypted' => 'Encrypted',
                ],
                'users' => [
                    'title' => 'System Operators',
                    'subtitle' => 'Provision and manage access for the',
                    'node' => 'node.',
                    'provision_btn' => 'Provision User',
                    'filters' => 'Filters:',
                    'filter_status' => 'Status',
                    'all_status' => 'All Status',
                    'filter_role' => 'Role',
                    'all_roles' => 'All Roles',
                    'joined' => 'Joined:',
                    'search_placeholder' => 'Filter by name or email...',
                    'edit_profile' => 'Edit Profile',
                    'new_team_member' => 'New Team Member',
                    'edit_desc' => 'Update clearance and details.',
                    'new_desc' => 'Provision a new system operator.',
                    'profile_photo' => 'Profile Photo',
                    'photo_reqs' => 'JPG, GIF or PNG. Max 2MB.',
                    'remove_photo' => 'Remove Photo',
                    'full_name' => 'Full Name',
                    'email_address' => 'Email Address',
                    'clearance_level' => 'Clearance Level',
                    'select_role' => 'Select Role',
                    'encryption_key' => 'Encryption Key',
                    'unchanged' => 'Leave blank to keep current',
                    'unchanged_placeholder' => 'Unchanged...',
                    'generate_pass' => 'Generate Strong Password',
                    'user_id' => 'User ID',
                    'col_operator' => 'Operator',
                    'col_clearance' => 'Clearance Level',
                    'col_status' => 'Status',
                    'col_provisioned' => 'Provisioned',
                    'col_actions' => 'Actions',
                    'purge_operator' => 'Purge Operator?',
                    'purge_desc' => 'This will permanently delete',
                    'purge_desc2' => 'from this node.',
                    'confirm_purge' => 'Confirm Purge',
                    'user_provisioned' => 'User provisioned',
                    'user_updated' => 'User updated',
                    'user_purged' => 'User purged',
                    'access' => 'User access',
                    'purge_protected_err' => 'Cannot purge protected accounts.',
                    'accounts_purged' => 'accounts purged.',
                    'protected_user' => 'This profile is protected and cannot be edited.',
                ],
                'roles' => [
                    'title' => 'Access Control Matrix',
                    'subtitle' => 'Define clearance levels and cryptographically bind them to network capabilities.',
                    'provision_btn' => 'New Clearance Level',
                    'search_placeholder' => 'Filter clearance levels...',
                    'modify_title' => 'Modify Clearance Level',
                    'establish_title' => 'Establish Clearance Level',
                    'dialog_desc' => 'Configure role identity and assign network capabilities.',
                    'designation' => 'Clearance Designation',
                    'assign_caps' => 'Assign Capabilities',
                    'search_perms' => "Search permissions...",
                    'toggle_all' => 'Toggle All Below',
                    'available' => 'Available',
                    'no_perms_match' => 'No capabilities match',
                    'active_caps' => 'Active Capabilities',
                    'available_caps' => 'Available Capabilities',
                    'update_matrix' => 'Update Matrix',
                    'deploy_clearance' => 'Deploy Clearance',
                    'caps_overview' => 'Network Capabilities Overview',
                    'god_mode_engaged' => '[ GOD MODE ENGAGED ]',
                    'god_mode_desc' => 'This clearance level inherently bypasses all network security protocols. Even if specific capabilities are unchecked below, this role maintains absolute read/write authority over the entire node.',
                    'explicit_caps' => 'Explicitly Bound Capabilities',
                    'no_caps_assigned' => 'No individual capabilities explicitly assigned.',
                    'close_view' => 'Close Overview',
                    'col_designation' => 'Clearance Level',
                    'col_capabilities' => 'Network Capabilities',
                    'col_established' => 'Established',
                    'col_actions' => 'Actions',
                    'god_mode' => 'ALL PROTOCOLS (GOD MODE)',
                    'no_access' => 'No Access',
                    'purge_title' => 'Purge Clearance Level?',
                    'purge_desc1' => 'This will permanently delete the',
                    'purge_desc2' => 'role. Operators assigned to this role may lose network access.',
                    'confirm_purge' => 'Confirm Purge',
                    'purge_core_err' => 'Cannot purge core system roles.',
                    'levels_purged' => 'clearance levels purged.',
                    'super_admin_err' => 'Super Admin cannot be modified.',
                    'admin_warn' => 'Core Role: You can modify capabilities, but the designation cannot be changed.',
                    'name_required' => 'Clearance level requires a designation.',
                    'updated' => 'Clearance level updated',
                    'established' => 'Clearance level established',
                ],
                'permissions' => [
                    'title' => 'Capability Dictionary',
                    'subtitle' => 'A read-only glossary of all hardcoded network capabilities available in the system.',
                    'indexed' => 'Indexed Protocols',
                    'search_placeholder' => 'Search capability codes...',
                    'col_code' => 'Capability Code',
                    'col_desc' => 'Human-Readable Context',
                    'col_scope' => 'Security Scope',
                    'col_actions' => 'Actions',
                    'allows_operator' => 'Allows the operator to',
                    'within_env' => 'within the active environment.',
                    'tenant_node' => 'Tenant Node',
                    'central' => 'Central Command',
                ],
                'tenants' => [
                    'title' => 'Node Management',
                    'subtitle' => 'Provision, monitor, and configure active tenant databases within the ecosystem.',
                    'verifying' => 'Verifying Network Clearance...',
                    'provisioned' => 'Node provisioned.',
                    'updated' => 'Node updated.',
                    'nodes_purged' => 'nodes purged.',
                    'provision_btn' => 'Provision Node',
                    'reconfigure' => 'Reconfigure Node',
                    'provision_new' => 'Provision New Node',
                    'infra' => 'Node Infrastructure',
                    'org_name' => 'Organization Name',
                    'node_id' => 'Node ID',
                    'plan' => 'Capacity Plan',
                    'domain' => 'Routing Address',
                    'super_admin' => 'Super Admin Settings',
                    'operator_name' => 'Operator Name',
                    'email' => 'Email',
                    'access_key' => 'Access Key',
                    'col_id' => 'Node ID',
                    'col_org' => 'Organization Name',
                    'col_plan' => 'Capacity Plan',
                    'col_domain' => 'Routing Address',
                    'col_status' => 'Node Status',
                    'col_provisioned' => 'Provisioned',
                    'col_actions' => 'Actions',
                    'purge_title' => 'Purge Node?',
                    'purge_desc' => 'This will permanently delete',
                    'purge_desc2' => 'and all data.',
                    'purge_confirm' => 'Confirm Purge',
                    'search_placeholder' => 'Filter nodes by ID or name...',
                    'view_title' => 'View Details',
                    'view_identity' => 'Node Identity',
                    'view_status' => 'Network Status',
                    'view_plan' => 'Capacity Plan',
                    'view_domain' => 'Routing Domain',
                    'view_contact' => 'Super Admin Contact',
                    'no_email' => 'No email registered',
                    'close_view' => 'Close Overview',
                ],
                'audit' => [
                    'title' => 'System Audit Logs',
                    'subtitle' => 'Cryptographically secure, immutable record of all network activity.',
                    'verifying' => 'Verifying Clearance...',
                    'active_logs' => 'Active Live Logs',
                    'vault' => 'Cold Storage Vault',
                    'clear_selection' => 'Clear Selection',
                    'delete_selected' => 'Permanently Delete Selected',
                    'filter_all' => 'All Activity',
                    'filter_crud' => 'Modifications',
                    'filter_telemetry' => 'Telemetry',
                    'filter_system' => 'System',
                    'node_all' => 'All Nodes',
                    'node_central' => 'Central',
                    'node_tenant' => 'Tenants',
                    'today' => 'Today',
                    'policy_settings' => 'Policy Settings',
                    'trigger_vault' => 'Trigger Vault',
                    'archiving' => 'Archiving...',
                    'policy_updated' => 'Policy updated.',
                    'engage_archive_title' => 'Engage the Archiving Engine?',
                    'engage_archive_desc' => 'This will systematically move all eligible live logs to the cold storage Vault based on your retention settings. This action cannot be reversed.',
                    'archive_btn' => 'Archive Logs',
                    'archive_success' => 'Archiving engine engaged. Check the Vault tab shortly.',
                    'delete_record_title' => 'Permanently Delete Record?',
                    'delete_record_desc' => 'You are about to permanently destroy this WORM vaulted record. This action violates standard audit compliance and cannot be undone.',
                    'record_deleted' => 'Vaulted record permanently deleted.',
                    'bulk_delete_title' => 'Bulk Delete Vaulted Records?',
                    'bulk_delete_desc' => 'You are about to permanently destroy selected vaulted records. This completely wipes them from the database and cannot be undone.',
                    'destroy_records' => 'Destroy Records',
                    'records_deleted' => 'vaulted records permanently deleted.',
                    'col_id' => 'ID',
                    'col_action' => 'Action',
                    'col_desc' => 'Activity Description',
                    'col_module' => 'Module',
                    'col_operator' => 'Operator',
                    'col_time' => 'Timestamp',
                    'col_actions' => 'Actions',
                    'col_node' => 'Node',
                    'settings_title' => 'Archive Policy Settings',
                    'settings_desc' => 'Configure the threshold for the automated WORM Archival Engine.',
                    'retention' => 'Retention Threshold (Days)',
                    'retention_1' => 'Logs older than',
                    'retention_days' => 'days',
                    'retention_2' => 'will be vaulted.',
                    'save_policy' => 'Save Policy',
                    'inspection' => 'Forensic Inspection',
                    'worm_id' => 'WORM Record ID',
                    'exec_desc' => 'Execution Description',
                    'payload' => 'Raw Payload Block',
                    'verified' => 'Integrity Verified',
                    'close_inspection' => 'Close Inspection',
                ],
                'tour' => [
                    'node_mgmt_title' => 'Node Management',
                    'node_mgmt_desc' => 'This is the master command center for all active tenant nodes on the HIVE.OS network.',
                    'provision_title' => 'Provision a Node',
                    'provision_desc' => 'Click here to allocate new infrastructure. You will define the organization name, capacity plan, and establish super admin credentials.',
                    'matrix_search_title' => 'Matrix Search',
                    'matrix_search_desc' => 'Filter the active node list instantly by ID or Organization Name.',
                    'copy_title' => 'Copy to Clipboard',
                    'copy_desc' => 'Quickly copy the current view to your clipboard for sharing.',
                    'export_title' => 'Export Data',
                    'export_desc' => 'Download the complete dataset in your preferred format (CSV, Excel).',
                    'print_title' => 'Print Matrix',
                    'print_desc' => 'Send the current configuration list to your PDF/Print processor.',
                    'refresh_title' => 'Force Sync',
                    'refresh_desc' => 'Manually refresh the datatable to pull the latest telemetry from the network.',
                    'matrix_title' => 'The Matrix',
                    'matrix_desc' => 'Monitor real-time network status.',
                    'inspect_title' => 'Inspect Node',
                    'inspect_desc' => 'View deep metrics, routing domains, and active capacity plans for this specific node.',
                    'power_title' => 'Network Power',
                    'power_desc' => 'Instantly suspend or restore network access for this tenant database.',
                    'clearance_title' => 'Operator Clearance',
                    'clearance_desc' => 'Enable or disable Super Admin login capabilities.',
                    'reconfig_title' => 'Reconfigure Node',
                    'reconfig_desc' => 'Update the organization name, adjust the capacity plan, or modify routing rules.',
                    'purge_title' => 'Purge Protocol',
                    'purge_desc' => 'Permanently delete this node and destroy all associated telemetry data. Use with extreme caution.',
                    'audit_title' => 'System Audit Logs',
                    'audit_desc' => 'This immutable ledger cryptographically records every action taken across the network.',
                    'ledger_title' => 'Ledger Views',
                    'ledger_desc' => 'Switch between the fast-access Active Live Logs and the deep Cold Storage Vault.',
                    'scope_title' => 'Node Scope',
                    'scope_desc' => 'Filter telemetry strictly from Central Command or specific Tenant Nodes.',
                    'time_title' => 'Time Dilations',
                    'time_desc' => 'Quickly jump to specific timeframes or set custom date boundaries to hunt for events.',
                    'vault_title' => 'Vault Controls',
                    'vault_desc' => 'Configure automated retention policies or manually trigger a cold storage sweep.',
                    'deep_search_title' => 'Deep Search',
                    'deep_search_desc' => 'Search the ledger instantly by operator name, description, or module.',
                    'forensic_title' => 'Forensic Inspection',
                    'forensic_desc' => 'Inspect the raw JSON payload and exact metadata footprint of a specific event.',
                    'tabs_nav_title' => 'Identity Matrix Navigation',
                    'tabs_nav_desc' => 'Switch between System Operators, Access Roles, and core Network Permissions here.',
                    'users_header_title' => 'System Operators',
                    'users_header_desc' => 'Manage all human and machine accounts operating within this node.',
                    'users_provision_title' => 'Provision Operator',
                    'users_provision_desc' => 'Create a new operator identity and assign them a clearance level.',
                    'users_search_desc' => 'Instantly find operators by name or email.',
                    'users_export_desc' => 'Download the operator list securely.',
                    'users_view_title' => 'Inspect Identity',
                    'users_view_desc' => 'View detailed metrics and activity for this operator.',
                    'users_status_title' => 'Toggle Access',
                    'users_status_desc' => 'Instantly lock or unlock an operator\'s network connection.',
                    'users_edit_desc' => 'Modify clearance levels or reset encryption keys.',
                    'users_purge_desc' => 'Permanently revoke access and destroy the identity.',
                    'roles_tab_desc' => 'The system has automatically switched to the Access Roles matrix. Click Next to explore.',
                    'roles_header_desc' => 'Define what operators can and cannot do within the ecosystem.',
                    'roles_provision_title' => 'New Clearance Level',
                    'roles_provision_desc' => 'Establish a new role and bind cryptographic capabilities to it.',
                    'roles_search_desc' => 'Search for specific clearance levels.',
                    'roles_copy_desc' => 'Copy the roles configuration to your clipboard.',
                    'roles_export_desc' => 'Download the clearance level matrix securely.',
                    'roles_print_desc' => 'Generate a printable report of all roles.',
                    'roles_refresh_desc' => 'Pull the latest capabilities from the network.',
                    'roles_view_title' => 'Inspect Clearance',
                    'roles_view_desc' => 'Review the exact capabilities bound to this role.',
                    'roles_edit_title' => 'Modify Clearance',
                    'roles_edit_desc' => 'Add or remove capabilities.',
                    'roles_purge_title' => 'Purge Clearance',
                    'roles_purge_desc' => 'Delete this role entirely.',
                    'perms_tab_desc' => 'Finally, the system has opened the Capability Dictionary.',
                    'perms_header_title' => 'Capability Dictionary',
                    'perms_header_desc' => 'A read-only ledger of all hardcoded network permissions.',
                    'perms_search_desc' => 'Search for specific capability codes.',
                    'perms_copy_desc' => 'Copy the dictionary mapping to your clipboard.',
                    'perms_export_desc' => 'Download the full capabilities list.',
                    'perms_print_desc' => 'Print the system capabilities dictionary.',
                    'perms_refresh_desc' => 'Verify the latest indexed protocols.',
                    'topbar_search_title' => 'Global Search',
                    'topbar_search_desc' => 'Quickly find users, nodes, or settings across the entire ecosystem.',
                    'topbar_lang_title' => 'Localization Engine',
                    'topbar_lang_desc' => 'Switch the system language instantly. Translations are fetched dynamically from the live matrix.',
                    'topbar_theme_title' => 'Interface Theme',
                    'topbar_theme_desc' => 'Toggle between light, dark, or system-default visual modes.',
                    'topbar_fullscreen_title' => 'Focus Mode',
                    'topbar_fullscreen_desc' => 'Expand the dashboard to fill your entire screen for maximum focus.',
                    'topbar_notif_title' => 'System Alerts',
                    'topbar_notif_desc' => 'Review critical security alerts, system updates, and node status changes here.',
                    'topbar_profile_title' => 'Operator Profile',
                    'topbar_profile_desc' => 'Access your personal settings, view your active clearance level, or safely disconnect from the node.',
                    'nav_overview_title' => 'Dashboard Overview',
                    'nav_overview_desc' => 'Your main telemetry and system status view.',
                    'nav_tenants_title' => 'Node Management',
                    'nav_tenants_desc' => 'Provision and monitor isolated tenant databases.',
                    'nav_security_title' => 'Identity & Access',
                    'nav_security_desc' => 'Manage system operators, access roles, and network capabilities.',
                    'nav_audit_title' => 'System Audit Logs',
                    'nav_audit_desc' => 'Review cryptographic, immutable records of all network activity.',
                    'nav_storage_title' => 'Storage Management',
                    'nav_storage_desc' => 'Manage system storage, file uploads, and capacity limits.',
                    'nav_settings_title' => 'System Preferences',
                    'nav_settings_desc' => 'Configure global settings, security policies, and localizations.',
                    'sidebar_brand_title' => 'HIVE.OS Control Hub',
                    'sidebar_brand_desc' => 'This is your central command console. Let\'s take a quick look at the tools available to you.',
                    'sidebar_nav_title' => 'Primary Navigation',
                    'sidebar_nav_desc' => 'Access the Dashboard, Node Management, Security Matrix, and Audit Logs from here.',
                    'sidebar_secondary_title' => 'System Preferences',
                    'sidebar_secondary_desc' => 'Manage storage capacity, global settings, and toggle your interface theme.',
                ]
            ],
            'am' => [
                'global' => [
                    'cancel' => 'ሰርዝ',
                    'update' => 'አዘምን',
                    'provision' => 'አቅርብ',
                    'delete' => 'ሰርዝ',
                    'purge' => 'አጥፋ',
                    'clear' => 'አጽዳ',
                    'save_changes' => 'ለውጦችን አስቀምጥ',
                    'page_tour' => 'የገጽ ጉብኝት',
                    'clearance_denied' => 'መዳረሻ ተከልክሏል',
                    'lacks_permission' => 'የአሁኑ መዳረሻዎ አስፈላጊውን አቅም ይጎድለዋል',
                    'capability' => 'አቅም።',
                    'operation_failed' => 'ክዋኔው አልተሳካም።',
                    'online' => 'በመስመር ላይ',
                    'suspended' => 'ታግዷል',
                    'active' => 'ንቁ',
                    'locked' => 'ተቆልፏል',
                    'restored' => 'ተመልሷል',
                    'created' => 'ተፈጥሯል',
                    'updated' => 'ተዘምኗል',
                    'deleted' => 'ተሰርዟል',
                    'viewed' => 'ታይቷል',
                    'exported' => 'ወደ ውጭ ተልኳል',
                    'copied' => 'ተቀድቷል',
                    'printed' => 'ታተመ',
                    'access_denied' => 'መዳረሻ ተከልክሏል',
                    'actions' => 'እርምጃዎች',
                    'view' => 'ዝርዝሮችን ይመልከቱ',
                    'edit' => 'አርትዕ',
                    'all' => 'ሁሉም',
                    'more' => 'ተጨማሪ',
                ],
                'auth' => [
                    'login' => 'ግባ',
                    'logout' => 'ውጣ',
                    'failed' => 'የተሳሳተ መረጃ ነው።'
                ],
                'nav' => [
                    'dashboard' => 'ዳሽቦርድ',
                    'tenants' => 'የተከራይ ኖዶች',
                    'security' => 'ማንነት እና መዳረሻ',
                    'audit_logs' => 'የስርዓት ኦዲት መዝገቦች',
                    'storage' => 'ማከማቻ',
                    'settings' => 'የስርዓት ምርጫዎች',
                    'profile' => 'የመገለጫ ቅንብሮች',
                    'control_hub' => 'የመቆጣጠሪያ ማዕከል',
                    'disconnect' => 'ኖዱን አቋርጥ',
                    'theme' => 'ገጽታ',
                    'close' => 'ዝጋ',
                    'settings_general' => 'ጠቅላላ',
                    'settings_general_desc' => 'መሰረታዊ የስርዓት ውቅር።',
                    'settings_security_desc' => 'የማረጋገጫ እና የመዳረሻ ፖሊሲዎች።',
                    'settings_loc' => 'ቋንቋ መቀየሪያ',
                    'settings_loc_desc' => 'ተለዋዋጭ የስርዓት ቋንቋዎችን ያስተዳድሩ።',
                    'settings_notif' => 'ማሳወቂያዎች',
                    'settings_notif_desc' => 'የኢሜል እና የስርዓት ማንቂያዎች።',
                    'settings_locked' => 'ውቅረት ተቆልፏል',
                    'settings_audit_msg' => 'ማትሪክስ በአሁኑ ጊዜ የደህንነት ኦዲት እየተደረገበት ነው። ሞጁሎች በሚቀጥለው ጥገኝ ይከፈታሉ።',
                ],
                'topbar' => [
                    'search' => 'ስርዓቱን ይፈልጉ...',
                    'system_tour' => 'የስርዓት ጉብኝት',
                    'change_language' => 'ቋንቋ ቀይር',
                    'select_language' => 'ቋንቋ ይምረጡ',
                    'my_account' => 'የእኔ መለያ',
                    'profile_settings' => 'የመገለጫ ቅንብሮች'
                ],
                'dashboard' => [
                    'node' => 'ኖድ',
                    'plan' => 'እቅድ',
                    'description' => 'የስርዓት ቴሌሜትሪ፣ የመዳረሻ ቁጥጥር እና የቅጽበታዊ ስራዎች።',
                    'realtime_activity' => 'የቅጽበታዊ እንቅስቃሴ',
                    'revenue_viz' => '[ የገቢ እይታ እዚህ ይጫናል ]',
                    'system_metrics' => 'የስርዓት መለኪያዎች',
                    'gross_revenue' => 'አጠቃላይ ገቢ',
                    'active_staff' => 'ንቁ ሰራተኞች',
                    'pending_tasks' => 'በመጠባበቅ ላይ ያሉ ተግባራት',
                    'recent_logs' => 'የቅርብ ጊዜ የኦዲት መዝገቦች',
                    'no_activity' => 'ምንም የቅርብ ጊዜ እንቅስቃሴ አልተገኘም።',
                    'storage_desc' => 'በተመቻቸ አቅም የሚሰሩ የተከራይ ፋይል ስርዓቶች።',
                    'decrypting' => 'የኖድ ቴሌሜትሪን በመፍታት ላይ...',
                    'connection_failed' => 'የኖድ ግንኙነት አልተሳካም',
                    'connection_error' => 'ከቴሌሜትሪ ጋር መገናኘት አልተሳካም።'
                ],
                'localization' => [
                    'title' => 'የማትሪክስ አስተዳዳሪ',
                    'publish_project' => 'ፕሮጀክቱን አትም',
                    'system_folders' => 'የስርዓት ቋንቋ አቃፊዎች',
                    'master_source' => 'ዋና ምንጭ',
                    'set_master' => 'እንደ ዋና ምንጭ አዘጋጅ',
                    'purge_lang_tooltip' => 'ቋንቋን አጥፋ',
                    'purge_lang_title' => 'የቋንቋ ማትሪክሱን አጥፋ?',
                    'purge_lang_desc' => 'ከባድ ማስጠንቀቂያ፡ እርግጠኛ ነዎት ይህን ሙሉ በሙሉ ማጥፋት ይፈልጋሉ',
                    'purge_lang_desc2' => 'የቋንቋ ማትሪክስ? ይህ ለዚህ ቋንቋ ሁሉንም ትርጉሞች እና አካላዊ ፋይሎች ያጠፋል። ይህ እርምጃ ወደነበረበት ሊመለስ አይችልም።',
                    'edit_dict' => 'መዝገበ ቃላትን አርትዕ',
                    'register_new' => 'አዲስ የቋንቋ አቃፊ ይመዝገቡ',
                    'create_lang' => 'ቋንቋ ፍጠር',
                    'lang_name_placeholder' => 'የቋንቋ ስም (ለምሳሌ አማርኛ)',
                    'iso_code_placeholder' => 'የISO ኮድ (ለምሳሌ am)',
                    'establish' => 'አቋቁም',
                    'node' => 'ኖድ',
                    'folder' => 'አቃፊ፡',
                    'filter_matrix' => 'ማትሪክስ አጣራ...',
                    'publish_btn' => 'አትም',
                    'add_key_btn' => 'ቁልፍ ያክሉ',
                    'json_files' => 'የJSON ፋይሎች',
                    'all_files' => 'ሁሉም ፋይሎች',
                    'system_id' => 'የስርዓት መለያ',
                    'master' => 'ዋና',
                    'entry' => 'ግቤት',
                    'no_keys' => 'በዚህ እይታ ምንም የስርዓት ቁልፎች አልተገኙም',
                    'input_string' => 'ጽሑፍ ያስገቡ...',
                    'purge_key_tooltip' => 'ቁልፍን አጥፋ',
                    'purge_key_title' => 'የስርዓት ቁልፍን አጥፋ?',
                    'purge_key_desc' => 'በእርግጠኝነት በቋሚነት መሰረዝ ይፈልጋሉ',
                    'purge_key_desc2' => 'ከዓለም አቀፍ ስርዓት? ይህ ከሁሉም የቋንቋ ማትሪክሶች ያስወግደዋል።',
                    'add_key_title' => 'ወደ ፋይል ቁልፍ አክል',
                    'global_sys_key' => 'ዓለም አቀፍ የስርዓት ቁልፍ',
                    'file_name' => 'የፋይል ስም',
                    'file_name_placeholder' => 'ለምሳሌ auth',
                    'key_name' => 'የቁልፍ ስም',
                    'key_name_placeholder' => 'ለምሳሌ login_title',
                    'master_value' => 'ዋና እሴት',
                    'master_value_placeholder' => 'የሚተረጎመው ጽሑፍ...',
                    'discard' => 'አስወግድ',
                    'inject_key' => 'ቁልፍ አስገባ',
                    'toast_key_req' => 'ቁልፍ እና ዋና ጽሑፍ ያስፈልጋል',
                    'toast_group_req' => 'የፋይል ቡድን ባዶ መሆን አይችልም',
                    'toast_key_added' => 'ቁልፍ ታክሏል ወደ',
                    'toast_key_purged' => 'ጠፍቷል።',
                    'toast_lang_purged' => 'ከስርዓቱ ሙሉ በሙሉ ጠፍቷል።',
                    'toast_compiling' => 'የJSON ፋይሎችን በማዘጋጀት ላይ...',
                    'toast_published' => 'አቃፊዎች እና ፋይሎች በተሳካ ሁኔታ ታትመዋል!',
                    'toast_failed' => 'ማተም አልተሳካም',
                    'engine_title' => 'የአካባቢያዊነት ሞተር',
                    'engine_desc' => 'ለዚህ ኖድ ተለዋዋጭ ትርጉሞችን እና የቋንቋ ፋይሎችን ያስተዳድሩ።',
                ],
                'security' => [
                    'identity' => 'ማንነት',
                    'access' => 'መዳረሻ',
                    'node_clearance' => 'የኖድ ፍቃድ',
                    'denied_desc' => 'የአሁኑ ፍቃድዎ ወደ ማንነት እና ደህንነት ማትሪክስ መዳረሻ አይፈቅድም።',
                    'tab_operators' => 'ኦፕሬተሮች',
                    'tab_roles' => 'የመዳረሻ ሚናዎች',
                    'tab_permissions' => 'ፈቃዶች',
                    'matrix_tour' => 'የማትሪክስ ጉብኝት',
                    'encrypted' => 'የተመሰጠረ',
                ],
                'users' => [
                    'title' => 'የስርዓት ኦፕሬተሮች',
                    'subtitle' => 'መዳረሻን ያቅርቡ እና ያስተዳድሩ ለ',
                    'node' => 'ኖድ።',
                    'provision_btn' => 'ተጠቃሚ አቅርብ',
                    'filters' => 'ማጣሪያዎች:',
                    'filter_status' => 'ሁኔታ',
                    'all_status' => 'ሁሉም ሁኔታ',
                    'filter_role' => 'ሚና',
                    'all_roles' => 'ሁሉም ሚናዎች',
                    'joined' => 'የተቀላቀለበት:',
                    'search_placeholder' => 'በስም ወይም በኢሜል አጣራ...',
                    'edit_profile' => 'መገለጫ አርትዕ',
                    'new_team_member' => 'አዲስ የቡድን አባል',
                    'edit_desc' => 'ፍቃዶችን እና ዝርዝሮችን ያዘምኑ።',
                    'new_desc' => 'አዲስ የስርዓት ኦፕሬተር ያቅርቡ።',
                    'profile_photo' => 'የመገለጫ ፎቶ',
                    'photo_reqs' => 'JPG, GIF ወይም PNG. ከፍተኛ 2MB.',
                    'remove_photo' => 'ፎቶ አስወግድ',
                    'full_name' => 'ሙሉ ስም',
                    'email_address' => 'የኢሜል አድራሻ',
                    'clearance_level' => 'የፈቃድ ደረጃ',
                    'select_role' => 'ሚና ይምረጡ',
                    'encryption_key' => 'የምስጠራ ቁልፍ',
                    'unchanged' => 'ያለውን ለማቆየት ባዶ ይተዉት',
                    'unchanged_placeholder' => 'ያልተለወጠ...',
                    'generate_pass' => 'ጠንካራ የይለፍ ቃል ይፍጠሩ',
                    'user_id' => 'የተጠቃሚ መታወቂያ',
                    'col_operator' => 'ኦፕሬተር',
                    'col_clearance' => 'የፈቃድ ደረጃ',
                    'col_status' => 'ሁኔታ',
                    'col_provisioned' => 'የቀረበበት ጊዜ',
                    'col_actions' => 'እርምጃዎች',
                    'purge_operator' => 'ኦፕሬተሩን አጥፋ?',
                    'purge_desc' => 'ይህ በቋሚነት ይሰርዛል',
                    'purge_desc2' => 'ከዚህ ኖድ።',
                    'confirm_purge' => 'ማጥፋት አረጋግጥ',
                    'user_provisioned' => 'ተጠቃሚ ቀርቧል',
                    'user_updated' => 'ተጠቃሚ ተዘምኗል',
                    'user_purged' => 'ተጠቃሚ ጠፍቷል',
                    'access' => 'የተጠቃሚ መዳረሻ',
                    'purge_protected_err' => 'የተጠበቁ መለያዎችን ማጥፋት አይቻልም።',
                    'accounts_purged' => 'መለያዎች ጠፍተዋል።',
                    'protected_user' => 'ይህ መገለጫ የተጠበቀ ነው እና አርትዕ ማድረግ አይቻልም።',
                ],
                'tenants' => [
                    'title' => 'የኖድ አስተዳደር',
                    'subtitle' => 'በሥርዓቱ ውስጥ ያሉትን የተከራይ ዳታቤዞችን ያቅርቡ፣ ይቆጣጠሩ እና ያዋቅሩ።',
                    'verifying' => 'የአውታረ መረብ መዳረሻን በማረጋገጥ ላይ...',
                    'provisioned' => 'ኖድ ቀርቧል።',
                    'updated' => 'ኖድ ተዘምኗል።',
                    'nodes_purged' => 'ኖዶች ሙሉ በሙሉ ጠፍተዋል',
                    'provision_btn' => 'ኖድ አቅርብ',
                    'reconfigure' => 'ኖድ እንደገና አዋቅር',
                    'provision_new' => 'አዲስ ኖድ አቅርብ',
                    'infra' => 'የኖድ መሰረተ ልማት',
                    'org_name' => 'የድርጅት ስም',
                    'node_id' => 'የኖድ መታወቂያ',
                    'plan' => 'የአቅም እቅድ',
                    'domain' => 'የማዞሪያ አድራሻ',
                    'super_admin' => 'የዋና አስተዳዳሪ ቅንብሮች',
                    'operator_name' => 'የኦፕሬተር ስም',
                    'email' => 'ኢሜይል',
                    'access_key' => 'የመዳረሻ ቁልፍ',
                    'col_id' => 'የኖድ መታወቂያ',
                    'col_org' => 'የድርጅት ስም',
                    'col_plan' => 'የአቅም እቅድ',
                    'col_domain' => 'የማዞሪያ አድራሻ',
                    'col_status' => 'የኖድ ሁኔታ',
                    'col_provisioned' => 'የቀረበበት ጊዜ',
                    'col_actions' => 'እርምጃዎች',
                    'purge_title' => 'ኖዱን አጥፋ?',
                    'purge_desc' => 'ይህ ኖዱን እና ሁሉንም ውሂብ በቋሚነት ይሰርዛል:',
                    'purge_desc2' => '',
                    'purge_confirm' => 'ማጥፋት አረጋግጥ',
                    'search_placeholder' => 'ኖዶችን በመታወቂያ ወይም በስም አጣራ...',
                    'view_title' => 'ዝርዝሮችን ይመልከቱ',
                    'view_identity' => 'የኖድ ማንነት',
                    'view_status' => 'የአውታረ መረብ ሁኔታ',
                    'view_plan' => 'የአቅም እቅድ',
                    'view_domain' => 'የማዞሪያ አድራሻ',
                    'view_contact' => 'የዋና አስተዳዳሪ እውቂያ',
                    'no_email' => 'ምንም ኢሜይል አልተመዘገበም',
                    'close_view' => 'አጠቃላይ እይታውን ዝጋ',
                ],
                'audit' => [
                    'title' => 'የስርዓት ኦዲት መዝገቦች',
                    'subtitle' => 'በአውታረ መረቡ ላይ የተወሰዱ እያንዳንዱን እርምጃዎች ደህንነቱ የተጠበቀ ሪከርድ።',
                    'verifying' => 'መዳረሻን በማረጋገጥ ላይ...',
                    'active_logs' => 'ንቁ የቀጥታ መዝገቦች',
                    'vault' => 'የቀዝቃዛ ማከማቻ ካዝና',
                    'clear_selection' => 'ምርጫን አጽዳ',
                    'delete_selected' => 'የተመረጡትን በቋሚነት ሰርዝ',
                    'filter_all' => 'ሁሉም እንቅስቃሴዎች',
                    'filter_crud' => 'ማሻሻያዎች',
                    'filter_telemetry' => 'ቴሌሜትሪ',
                    'filter_system' => 'ስርዓት',
                    'node_all' => 'ሁሉም ኖዶች',
                    'node_central' => 'ማዕከላዊ',
                    'node_tenant' => 'ተከራዮች',
                    'today' => 'ዛሬ',
                    'policy_settings' => 'የፖሊሲ ቅንብሮች',
                    'trigger_vault' => 'ወደ ካዝና ላክ',
                    'archiving' => 'ወደ ማህደር በማስቀመጥ ላይ...',
                    'policy_updated' => 'ፖሊሲው ተዘምኗል።',
                    'engage_archive_title' => 'የማህደር ስርዓቱን ያስጀምሩ?',
                    'engage_archive_desc' => 'ይህ በቀጥታ ማህደር ማስቀመጥ አይቻልም።',
                    'archive_btn' => 'መዝገቦችን ማህደር አድርግ',
                    'archive_success' => 'ወደ ካዝና ተልኳል።',
                    'delete_record_title' => 'መዝገቡን በቋሚነት ሰርዝ?',
                    'delete_record_desc' => 'ይህ ድርጊት መደበኛ የኦዲት ህጎችን ይጥሳል እና ወደነበረበት ሊመለስ አይችልም።',
                    'record_deleted' => 'መዝገቡ በቋሚነት ተሰርዟል።',
                    'bulk_delete_title' => 'በርካታ መዝገቦችን ሰርዝ?',
                    'bulk_delete_desc' => 'ይህ ሙሉ በሙሉ ከዳታቤዙ ውስጥ ያጠፋቸዋል።',
                    'destroy_records' => 'መዝገቦችን አጥፋ',
                    'records_deleted' => 'መዝገቦች በቋሚነት ተሰርዘዋል።',
                    'col_id' => 'መታወቂያ',
                    'col_action' => 'እርምጃ',
                    'col_desc' => 'የእንቅስቃሴ መግለጫ',
                    'col_module' => 'ሞጁል',
                    'col_operator' => 'ኦፕሬተር',
                    'col_time' => 'የጊዜ ማህተም',
                    'col_actions' => 'እርምጃዎች',
                    'col_node' => 'ኖድ',
                    'settings_title' => 'የማህደር ፖሊሲ ቅንብሮች',
                    'settings_desc' => 'በራስ ሰር ወደ ካዝና ለመላክ የጊዜ ገደብ ያዋቅሩ።',
                    'retention' => 'የማቆያ ጊዜ (ቀናት)',
                    'retention_1' => 'ከ',
                    'retention_days' => 'ቀናት',
                    'retention_2' => 'በላይ የሆኑ መዝገቦች ወደ ካዝና ይላካሉ።',
                    'save_policy' => 'ፖሊሲ አስቀምጥ',
                    'inspection' => 'ፎረንሲክ ምርመራ',
                    'worm_id' => 'የመዝገብ መታወቂያ',
                    'exec_desc' => 'የአፈፃፀም መግለጫ',
                    'payload' => 'ጥሬ የውሂብ እገዳ',
                    'verified' => 'ትክክለኛነት ተረጋግጧል',
                    'close_inspection' => 'ምርመራውን ዝጋ',
                ],
                'roles' => [
                    'title' => 'የመዳረሻ መቆጣጠሪያ ማትሪክስ',
                    'subtitle' => 'የፈቃድ ደረጃዎችን ይግለጹ እና ከአውታረ መረብ ችሎታዎች ጋር ያያይዟቸው።',
                    'provision_btn' => 'አዲስ የፈቃድ ደረጃ',
                    'search_placeholder' => 'የፈቃድ ደረጃዎችን ያጣሩ...',
                    'modify_title' => 'የፈቃድ ደረጃን ያሻሽሉ',
                    'establish_title' => 'የፈቃድ ደረጃ ያዋቅሩ',
                    'dialog_desc' => 'የሚና ማንነትን ያዋቅሩ እና የአውታረ መረብ ችሎታዎችን ይመድቡ።',
                    'designation' => 'የፈቃድ ስያሜ',
                    'assign_caps' => 'ችሎታዎችን ይመድቡ',
                    'search_perms' => "ፈቃዶችን ይፈልጉ...",
                    'toggle_all' => 'ከታች ያሉትን ሁሉ ቀይር',
                    'available' => 'ይገኛል',
                    'no_perms_match' => 'ምንም ችሎታዎች አይዛመዱም',
                    'active_caps' => 'ንቁ ችሎታዎች',
                    'available_caps' => 'የሚገኙ ችሎታዎች',
                    'update_matrix' => 'ማትሪክስ አዘምን',
                    'deploy_clearance' => 'ፈቃድ ያሰማሩ',
                    'caps_overview' => 'የአውታረ መረብ ችሎታዎች አጠቃላይ እይታ',
                    'god_mode_engaged' => '[ የፈጣሪ ሞድ ነቅቷል ]',
                    'god_mode_desc' => 'ይህ የፈቃድ ደረጃ ሁሉንም የአውታረ መረብ ደህንነት ፕሮቶኮሎች ያልፋል። ከታች ያሉት ችሎታዎች ባይመረጡም፣ ይህ ሚና ሙሉ የስርዓት ባለስልጣንነት አለው።',
                    'explicit_caps' => 'በግልጽ የታሰሩ ችሎታዎች',
                    'no_caps_assigned' => 'ምንም የተመደቡ ችሎታዎች የሉም።',
                    'close_view' => 'እይታውን ዝጋ',
                    'col_designation' => 'የፈቃድ ደረጃ',
                    'col_capabilities' => 'የአውታረ መረብ ችሎታዎች',
                    'col_established' => 'የተመሰረተበት',
                    'col_actions' => 'እርምጃዎች',
                    'god_mode' => 'ሁሉም ፕሮቶኮሎች (GOD MODE)',
                    'no_access' => 'መዳረሻ የለም',
                    'purge_title' => 'የፈቃድ ደረጃን አጥፋ?',
                    'purge_desc1' => 'ይህ በሚከተለው ይሰርዛል:',
                    'purge_desc2' => 'ሚና። በዚህ ሚና የተመደቡ ኦፕሬተሮች የአውታረ መረብ መዳረሻ ሊያጡ ይችላሉ።',
                    'confirm_purge' => 'ማጥፋት አረጋግጥ',
                    'purge_core_err' => 'ዋና የስርዓት ሚናዎችን ማጥፋት አይቻልም።',
                    'levels_purged' => 'የፈቃድ ደረጃዎች ጠፍተዋል።',
                    'super_admin_err' => 'ዋና አስተዳዳሪን መቀየር አይቻልም።',
                    'admin_warn' => 'ዋና ሚና፡ ችሎታዎችን ማሻሻል ይችላሉ፣ ግን ስያሜውን መለወጥ አይቻልም።',
                    'name_required' => 'የፈቃድ ደረጃ ስያሜ ይፈልጋል።',
                    'updated' => 'የፈቃድ ደረጃ ተዘምኗል',
                    'established' => 'የፈቃድ ደረጃ ተዋቅሯል',
                ],
                'permissions' => [
                    'title' => 'የችሎታ መዝገበ ቃላት',
                    'subtitle' => 'በስርዓቱ ውስጥ ያሉ የሁሉም አውታረ መረብ ችሎታዎች ተነባቢ-ብቻ ማውጫ።',
                    'indexed' => 'የተጠቆሙ ፕሮቶኮሎች',
                    'search_placeholder' => 'የችሎታ ኮዶችን ይፈልጉ...',
                    'col_code' => 'የችሎታ ኮድ',
                    'col_desc' => 'ሊነበብ የሚችል አውድ',
                    'col_scope' => 'የደህንነት ወሰን',
                    'col_actions' => 'እርምጃዎች',
                    'allows_operator' => 'ኦፕሬተሩ እንዲህ እንዲያደርግ ይፈቅዳል',
                    'within_env' => 'በአከባቢው ውስጥ።',
                    'tenant_node' => 'የተከራይ ኖድ',
                    'central' => 'ማዕከላዊ መቆጣጠሪያ',
                ],
                'tour' => [
                        // --- TOPBAR TOUR ---
                        'topbar_search_title' => 'ዓለም አቀፍ ፍለጋ',
                        'topbar_search_desc' => 'በጠቅላላው ስነ-ምህዳር ውስጥ ተጠቃሚዎችን፣ ኖዶችን ወይም ቅንብሮችን በፍጥነት ያግኙ።',
                        'topbar_lang_title' => 'የአካባቢያዊነት ሞተር',
                        'topbar_lang_desc' => 'የስርዓቱን ቋንቋ ወዲያውኑ ይቀይሩ። ትርጉሞች በቀጥታ ከማትሪክስ ይወሰዳሉ።',
                        'topbar_theme_title' => 'የገጽታ ጭብጥ',
                        'topbar_theme_desc' => 'በብርሃን፣ በጨለማ ወይም በስርዓት-ነባሪ የእይታ ሁነታዎች መካከል ይቀያይሩ።',
                        'topbar_fullscreen_title' => 'የትኩረት ሁነታ',
                        'topbar_fullscreen_desc' => 'ለከፍተኛ ትኩረት ዳሽቦርዱን መላውን ማያ ገጽዎ እንዲሞላ ያድርጉት።',
                        'topbar_notif_title' => 'የስርዓት ማንቂያዎች',
                        'topbar_notif_desc' => 'ወሳኝ የደህንነት ማንቂያዎችን፣ የስርዓት ዝመናዎችን እና የኖድ ሁኔታ ለውጦችን እዚህ ይገምግሙ።',
                        'topbar_profile_title' => 'የኦፕሬተር መገለጫ',
                        'topbar_profile_desc' => 'የግል ቅንብሮችዎን ይድረሱ፣ ንቁ የፈቃድ ደረጃዎን ይመልከቱ ወይም ከኖዱ በአስተማማኝ ሁኔታ ይውጡ።',

                        // --- TENANTS TOUR ---
                        'node_mgmt_title' => 'የኖድ አስተዳደር',
                        'node_mgmt_desc' => 'ይህ በስርዓቱ ላይ ላሉ ሁሉም የተከራይ ኖዶች ማስተዳደሪያ ነው።',
                        'provision_title' => 'ኖድ አቅርብ',
                        'provision_desc' => 'አዲስ መሰረተ ልማት ለመመደብ እዚህ ጠቅ ያድርጉ።',
                        'matrix_search_title' => 'ማትሪክስ ፍለጋ',
                        'matrix_search_desc' => 'ኖዶችን በመታወቂያ ወይም በስም ወዲያውኑ ያጣሩ።',
                        'copy_title' => 'ወደ ክሊፕቦርድ ቅዳ',
                        'copy_desc' => 'የአሁኑን እይታ ለሌሎች ለማጋራት ይቅዱ።',
                        'export_title' => 'ውሂብ ወደ ውጭ ላክ',
                        'export_desc' => 'ሙሉውን ዳታሴት በCSV ወይም በኤክሴል ያውርዱ።',
                        'print_title' => 'ማትሪክስ አትም',
                        'print_desc' => 'ኖዶችን በፒዲኤፍ ያትሙ።',
                        'refresh_title' => 'አስገድዶ አዘምን',
                        'refresh_desc' => 'ከአውታረ መረቡ የቅርብ ጊዜ መረጃዎችን ለመሳብ ጠረጴዛውን ያዘምኑ።',
                        'matrix_title' => 'የኖድ ማትሪክስ',
                        'matrix_desc' => 'የአውታረ መረቡን ሁኔታ በቅጽበት ይከታተሉ።',
                        'inspect_title' => 'ኖዱን መርምር',
                        'inspect_desc' => 'ስለዚህ የተወሰነ ኖድ ጥልቅ መረጃዎችን ይመልከቱ።',
                        'power_title' => 'የአውታረ መረብ ኃይል',
                        'power_desc' => 'የዚህን ኖድ ግንኙነት ወዲያውኑ ያግዱ ወይም ይመልሱ።',
                        'clearance_title' => 'የኦፕሬተር ፈቃድ',
                        'clearance_desc' => 'የዋና አስተዳዳሪን መግቢያ አንቃ ወይም አሰናክል።',
                        'reconfig_title' => 'ኖድ እንደገና አዋቅር',
                        'reconfig_desc' => 'የድርጅቱን ስም፣ እቅድ ወይም ማዞሪያ ያዘምኑ።',
                        'purge_title' => 'የማጥፋት ፕሮቶኮል',
                        'purge_desc' => 'ኖዱን በቋሚነት ለመሰረዝ ይህን ይጠቀሙ። በጥንቃቄ ይጠቀሙበት።',

                        // --- AUDIT LOGS TOUR ---
                        'audit_title' => 'የስርዓት ኦዲት መዝገቦች',
                        'audit_desc' => 'ይህ የማይለወጥ መዝገብ በአውታረ መረቡ ላይ የተወሰዱትን እርምጃዎች ይመዘግባል።',
                        'ledger_title' => 'የመዝገብ እይታዎች',
                        'ledger_desc' => 'በቀጥታ መዝገቦች እና በቀዝቃዛ ካዝና መካከል ይቀያይሩ።',
                        'scope_title' => 'የኖድ ወሰን',
                        'scope_desc' => 'ከማዕከላዊ ወይም ከተወሰኑ ተከራይ ኖዶች የተገኙ መረጃዎችን ያጣሩ።',
                        'time_title' => 'የጊዜ ክልል',
                        'time_desc' => 'ክስተቶችን ለመፈለግ የተወሰኑ ቀናትን ይምረጡ።',
                        'vault_title' => 'የካዝና መቆጣጠሪያዎች',
                        'vault_desc' => 'የማቆያ ፖሊሲዎችን ያዋቅሩ ወይም መዝገቦችን ወደ ካዝና ይላኩ።',
                        'deep_search_title' => 'ጥልቅ ፍለጋ',
                        'deep_search_desc' => 'በኦፕሬተር ስም፣ በመግለጫ ወይም በሞጁል ይፈልጉ።',
                        'forensic_title' => 'ፎረንሲክ ምርመራ',
                        'forensic_desc' => 'የአንድ ክስተት ትክክለኛ የውሂብ እገዳን እና ሜታዳታን ይመርምሩ።',

                        // --- SECURITY & IDENTITY TOUR ---
                        'tabs_nav_title' => 'የማንነት ማትሪክስ አሰሳ',
                        'tabs_nav_desc' => 'በስርዓት ኦፕሬተሮች፣ የመዳረሻ ሚናዎች እና የኔትወርክ ፈቃዶች መካከል እዚህ ይቀያይሩ።',
                        'users_header_title' => 'የስርዓት ኦፕሬተሮች',
                        'users_header_desc' => 'በዚህ ኖድ ውስጥ የሚሰሩትን ሁሉንም የሰዎች እና የማሽን መለያዎች ያስተዳድሩ።',
                        'users_provision_title' => 'ኦፕሬተር አቅርብ',
                        'users_provision_desc' => 'አዲስ የኦፕሬተር ማንነት ይፍጠሩ እና የፈቃድ ደረጃ ይመድቡላቸው።',
                        'users_search_desc' => 'በስም ወይም በኢሜል ኦፕሬተሮችን ወዲያውኑ ያግኙ።',
                        'users_export_desc' => 'የኦፕሬተር ዝርዝሩን በደህና ያውርዱ።',
                        'users_view_title' => 'ማንነትን መርምር',
                        'users_view_desc' => 'ስለዚህ ኦፕሬተር ዝርዝር መረጃዎችን ይመልከቱ።',
                        'users_status_title' => 'መዳረሻ ቀይር',
                        'users_status_desc' => 'የኦፕሬተሩን አውታረ መረብ ግንኙነት ወዲያውኑ ይቆልፉ ወይም ይክፈቱ።',
                        'users_edit_desc' => 'የፈቃድ ደረጃዎችን ወይም የምስጠራ ቁልፎችን ያሻሽሉ።',
                        'users_purge_desc' => 'መዳረሻን በቋሚነት ይሻሩ እና ማንነትን ያጥፉ።',

                        // --- ROLES & CLEARANCE TOUR ---
                        'roles_tab_desc' => 'ስርዓቱ በራስ ሰር ወደ የመዳረሻ ሚናዎች ማትሪክስ ተቀይሯል።',
                        'roles_header_desc' => 'ኦፕሬተሮች በስርዓቱ ውስጥ ምን ማድረግ እንደሚችሉ እና እንደማይችሉ ይግለጹ።',
                        'roles_provision_title' => 'አዲስ የፈቃድ ደረጃ',
                        'roles_provision_desc' => 'አዲስ ሚና ይፍጠሩ እና ችሎታዎችን ከእሱ ጋር ያያይዙ።',
                        'roles_search_desc' => 'የተወሰኑ የፈቃድ ደረጃዎችን ይፈልጉ።',
                        'roles_copy_desc' => 'የሚናዎቹን ውቅር ወደ ክሊፕቦርድዎ ይቅዱ።',
                        'roles_export_desc' => 'የፈቃድ ደረጃ ማትሪክሱን በደህና ያውርዱ።',
                        'roles_print_desc' => 'የሁሉም ሚናዎች ሊታተም የሚችል ሪፖርት ያመንጩ።',
                        'roles_refresh_desc' => 'ከአውታረ መረቡ የቅርብ ጊዜ ችሎታዎችን ይሳቡ።',
                        'roles_view_title' => 'ፈቃድን መርምር',
                        'roles_view_desc' => 'ከዚህ ሚና ጋር የተያያዙትን ትክክለኛ ችሎታዎች ይገምግሙ።',
                        'roles_edit_title' => 'ፈቃድን ያሻሽሉ',
                        'roles_edit_desc' => 'ችሎታዎችን ያክሉ ወይም ያስወግዱ።',
                        'roles_purge_title' => 'ፈቃድን አጥፋ',
                        'roles_purge_desc' => 'ይህን ሚና ሙሉ በሙሉ ይሰርዙ።',

                        // --- PERMISSIONS TOUR ---
                        'perms_tab_desc' => 'በመጨረሻም ስርዓቱ የችሎታ መዝገበ ቃላቱን ከፍቷል።',
                        'perms_header_title' => 'የችሎታ መዝገበ ቃላት',
                        'perms_header_desc' => 'የሁሉም አውታረ መረብ ፈቃዶች ተነባቢ-ብቻ መዝገብ።',
                        'perms_search_desc' => 'የተወሰኑ የችሎታ ኮዶችን ይፈልጉ።',
                        'perms_copy_desc' => 'የመዝገበ ቃላቱን ካርታ ወደ ክሊፕቦርድዎ ይቅዱ።',
                        'perms_export_desc' => 'ሙሉ የችሎታዎችን ዝርዝር ያውርዱ።',
                        'perms_print_desc' => 'የስርዓት ችሎታዎች መዝገበ ቃላትን ያትሙ።',
                        'perms_refresh_desc' => 'የቅርብ ጊዜዎቹን ፕሮቶኮሎች ያረጋግጡ።',

                        'nav_overview_title' => 'የዳሽቦርድ አጠቃላይ እይታ',
                        'nav_overview_desc' => 'የእርስዎ ዋና የስርዓት ሁኔታ እና ቴሌሜትሪ እይታ።',
                        'nav_tenants_title' => 'የኖድ አስተዳደር',
                        'nav_tenants_desc' => 'የተከለሉ የተከራይ ዳታቤዞችን ያቅርቡ እና ይቆጣጠሩ።',
                        'nav_security_title' => 'ማንነት እና መዳረሻ',
                        'nav_security_desc' => 'የስርዓት ኦፕሬተሮችን፣ የመዳረሻ ሚናዎችን እና የአውታረ መረብ ችሎታዎችን ያስተዳድሩ።',
                        'nav_audit_title' => 'የስርዓት ኦዲት መዝገቦች',
                        'nav_audit_desc' => 'የሁሉም የአውታረ መረብ እንቅስቃሴዎች የማይለወጡ የምስጠራ መዝገቦችን ይገምግሙ።',
                        'nav_storage_title' => 'የማከማቻ አስተዳደር',
                        'nav_storage_desc' => 'የስርዓት ማከማቻን፣ የፋይል ሰቀላዎችን እና የአቅም ገደቦችን ያስተዳድሩ።',
                        'nav_settings_title' => 'የስርዓት ምርጫዎች',
                        'nav_settings_desc' => 'ዓለም አቀፍ ቅንብሮችን፣ የደህንነት ፖሊሲዎችን እና ቋንቋዎችን ያዋቅሩ።',
                        'sidebar_brand_title' => 'የHIVE.OS መቆጣጠሪያ ማዕከል',
                        'sidebar_brand_desc' => 'ይህ የእርስዎ ማዕከላዊ የትእዛዝ ኮንሶል ነው። ለእርስዎ የሚገኙትን መሳሪያዎች በፍጥነት እንመልከት።',
                        'sidebar_nav_title' => 'ዋና ማሰሻ',
                        'sidebar_nav_desc' => 'ዳሽቦርድ፣ የኖድ አስተዳደር፣ የደህንነት ማትሪክስ እና የኦዲት መዝገቦችን ከዚህ ይድረሱ።',
                        'sidebar_secondary_title' => 'የስርዓት ምርጫዎች',
                        'sidebar_secondary_desc' => 'የማከማቻ አቅምን፣ ዓለም አቀፍ ቅንብሮችን ያስተዳድሩ እና በገጽታዎች መካከል ይቀያይሩ።',
                ],
            ]
        ];

        foreach ($defaultMatrix as $langCode => $files) {
            $dirPath = "{$langPath}/{$langCode}";

            if (!File::isDirectory($dirPath)) {
                File::makeDirectory($dirPath, 0775, true, true);
            }

            foreach ($files as $filename => $keys) {
                $filePath = "{$dirPath}/{$filename}.json";

                // Safety: Do not overwrite existing translation files
                if (!File::exists($filePath)) {
                    File::put($filePath, json_encode($keys, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
                }
            }
        }
    }
}
